### ISSUE TITLE
Cannot get package

### ISSUE THREAD

**Issue by Mocramis** [K4rian/winsock2-go#1]
I believe the go.mod should be in the parent directory, currently, running the install command returns an error:
`$ go get -u github.com/K4rian/winsock2-go/ws2                                                                                                                                                                                        
go: module github.com/K4rian/winsock2-go@upgrade found (v0.0.0-20240727160017-55c7cd708736), but does not contain package github.com/K4rian/winsock2-go/ws2`

Thanks for those very needed bindings btw :)

**Comment by K4rian** [comment]
Hi,

You're absolutely right. I've moved the go.mod file to the root directory (see commit d43aa39) to resolve the issue.

Thanks for pointing this out and for your interest in the project!

**Comment by Mocramis** [comment]
Thanks for the fix.

Works for me, however, do you need such a high go version ? the package does no seems to depends on any recent feature ...

**Comment by K4rian** [comment]
Hi,

You're right, whilst the latest security and bug fixes (1.22.X) don't directly impact the bindings (since they don't use the net package), it's generally a good practice to keep go projects up-to-date unless there are breaking changes.

I can revert to 1.22.0 if that's a concern for you. Unfortunately, I can't test the bindings on earlier major Go versions (<1.22.0) right now, but feel free to fork the project if you need to.

Thanks.

**Comment by Mocramis** [comment]
I'd prefer 1.22.0 if it is ok with you

**Comment by K4rian** [comment]
Resolved in 296f279.

**Comment by Mocramis** [comment]
Thanks !
